/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoHelpRouteImport } from './routes/demo.help'
import { Route as DemoHistoryRouteImport } from './routes/demo.history'
import { Route as DemoNewRouteImport } from './routes/demo.new'
import { Route as DemoSettingsRouteImport } from './routes/demo.settings'
import { Route as DemoReviewIdRouteImport } from './routes/demo.review.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoHelpRoute = DemoHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DemoRoute,
} as any)
const DemoHistoryRoute = DemoHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DemoRoute,
} as any)
const DemoNewRoute = DemoNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DemoRoute,
} as any)
const DemoSettingsRoute = DemoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DemoRoute,
} as any)
const DemoReviewIdRoute = DemoReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/help': typeof DemoHelpRoute
  '/demo/history': typeof DemoHistoryRoute
  '/demo/new': typeof DemoNewRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/review/$id': typeof DemoReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/help': typeof DemoHelpRoute
  '/demo/history': typeof DemoHistoryRoute
  '/demo/new': typeof DemoNewRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo': typeof DemoIndexRoute
  '/demo/review/$id': typeof DemoReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/help': typeof DemoHelpRoute
  '/demo/history': typeof DemoHistoryRoute
  '/demo/new': typeof DemoNewRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/review/$id': typeof DemoReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/demo/help'
    | '/demo/history'
    | '/demo/new'
    | '/demo/settings'
    | '/demo/'
    | '/demo/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/help'
    | '/demo/history'
    | '/demo/new'
    | '/demo/settings'
    | '/demo'
    | '/demo/review/$id'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/demo/help'
    | '/demo/history'
    | '/demo/new'
    | '/demo/settings'
    | '/demo/'
    | '/demo/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/help': {
      id: '/demo/help'
      path: '/help'
      fullPath: '/demo/help'
      preLoaderRoute: typeof DemoHelpRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/history': {
      id: '/demo/history'
      path: '/history'
      fullPath: '/demo/history'
      preLoaderRoute: typeof DemoHistoryRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/new': {
      id: '/demo/new'
      path: '/new'
      fullPath: '/demo/new'
      preLoaderRoute: typeof DemoNewRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/settings': {
      id: '/demo/settings'
      path: '/settings'
      fullPath: '/demo/settings'
      preLoaderRoute: typeof DemoSettingsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/review/$id': {
      id: '/demo/review/$id'
      path: '/review/$id'
      fullPath: '/demo/review/$id'
      preLoaderRoute: typeof DemoReviewIdRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface DemoRouteChildren {
  DemoHelpRoute: typeof DemoHelpRoute
  DemoHistoryRoute: typeof DemoHistoryRoute
  DemoNewRoute: typeof DemoNewRoute
  DemoSettingsRoute: typeof DemoSettingsRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoReviewIdRoute: typeof DemoReviewIdRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoHelpRoute: DemoHelpRoute,
  DemoHistoryRoute: DemoHistoryRoute,
  DemoNewRoute: DemoNewRoute,
  DemoSettingsRoute: DemoSettingsRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoReviewIdRoute: DemoReviewIdRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
